### ISSUE TITLE
minimal documentation

### ISSUE THREAD

**Issue by exponentus** [knowledgearc/jsolr#2]
Although I've managed to install all the relevant Joomla packages and created a new Solr collection to accommodate Joomla data, I don't know how to populate said collection.
Also, the correct placement of the solr/conf folder is a mystery to me.

In the connection settings of each component (search and index), I have specified the host and port where Solr is listening. However, I don't know which value should go in the path field.

A bit of guidance would be greatly appreciated.
Thanks.

**Comment by haydenyoung** [comment]
Hi

The solr/conf files are to be deployed to your /path/to/solr/instance/conf/. If you are running cores,  conf will be under the directory that matches your core's name.

Path will be everything in your solr url after the port number, so if, for example, you are running solr at http://localhost:8983/solr/my-solr then path will be /solr/my-solr. If you have no path then path will simply be a slash "/".

Hope this helps.

It's worth noting that we are building a completely new JSolr component using the Solarium library so the current 2.x distribution has not been maintained for some time. Also it is not overly user-friendly and probably has unaddressed bugs in it and the underlying Apache Solr server has moved on since we developed version 2 of JSolr.

New versions of JSolr will do away with the predefined conf as newer versions of Solr will allow us to deploy custom configurations of the Solr schema on the fly.

My point being it is probably worth waiting for the newer version of JSolr before using Solr as your Joomla search mechanism.

Thanks for you interest in JSolr.

**Comment by haydenyoung** [comment]
https://www.gitbook.com/book/knowledgearc/jsolr/details
